# Generated by Django 4.1 on 2022-08-31 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_userabout_date_of_birth_alter_userabout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='likes',
        ),
        migrations.AddField(
            model_name='assets',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='assets',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assets',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='blog.post'),
        ),
    ]
