# Generated by Django 4.1 on 2022-08-31 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userabout',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
