# Generated by Django 4.1 on 2022-09-03 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
