# Generated by Django 4.1 on 2022-09-03 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_rating_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
